#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include "dsp/NeuralFIRModel.h"

using namespace lyrebird;
using Catch::Matchers::WithinAbs;

TEST_CASE("NeuralFIRModel initialization", "[neural_model]") {
    NeuralFIRModel model;

    SECTION("default state") {
        REQUIRE_FALSE(model.isLoaded());
        REQUIRE(model.getBufferLength() == 512);
        REQUIRE(model.getHiddenSize() == 128);
        REQUIRE(model.getNumLayers() == 3);
        REQUIRE(model.getLatencySamples() == 512);
    }
}

TEST_CASE("NeuralFIRModel passthrough without model", "[neural_model]") {
    NeuralFIRModel model;

    SECTION("passes through input when no model loaded") {
        // Without a model loaded, processSample should return input
        for (int i = 0; i < 1000; ++i) {
            float input = static_cast<float>(i) / 1000.0f;
            float output = model.processSample(input);
            REQUIRE_THAT(output, WithinAbs(input, 0.0001f));
        }
    }
}

TEST_CASE("NeuralFIRModel reset", "[neural_model]") {
    NeuralFIRModel model;

    // Push some samples
    for (int i = 0; i < 600; ++i) {
        model.processSample(static_cast<float>(i) / 1000.0f);
    }

    // Reset
    model.reset();

    // After reset, should pass through initial samples again
    // (since we're back in buffer-fill mode)
    float testInput = 0.5f;
    float output = model.processSample(testInput);
    REQUIRE_THAT(output, WithinAbs(testInput, 0.0001f));
}

TEST_CASE("NeuralFIRModel invalid model path", "[neural_model]") {
    NeuralFIRModel model;

    SECTION("returns false for non-existent file") {
        REQUIRE_FALSE(model.loadModel("/nonexistent/path/model.json"));
        REQUIRE_FALSE(model.isLoaded());
    }
}

TEST_CASE("NeuralFIRModel config accessors", "[neural_model]") {
    NeuralFIRModel model;

    // These should match the compile-time ModelConfig
    REQUIRE(model.getBufferLength() == ModelConfig::BUFFER_LENGTH);
    REQUIRE(model.getHiddenSize() == ModelConfig::HIDDEN_SIZE);
    REQUIRE(model.getNumLayers() == ModelConfig::NUM_LAYERS);
}

TEST_CASE("NeuralFIRModel buffer fill behavior", "[neural_model]") {
    NeuralFIRModel model;

    SECTION("passthrough during buffer fill") {
        // For first BUFFER_LENGTH samples, should pass through
        for (int i = 0; i < ModelConfig::BUFFER_LENGTH; ++i) {
            float input = 0.1f * (i % 10);
            float output = model.processSample(input);
            REQUIRE_THAT(output, WithinAbs(input, 0.0001f));
        }
    }
}

// Inference tests using test model fixture
TEST_CASE("NeuralFIRModel inference with loaded model", "[neural_model][inference]") {
    NeuralFIRModel model;

    // Load test model (path relative to test executable location)
    // The test model is generated by generate_test_model.py
    bool loaded = model.loadModel("fixtures/test_model.json");

    // Skip tests if model couldn't be loaded (e.g., running from different directory)
    if (!loaded) {
        WARN("Test model not found at fixtures/test_model.json - skipping inference tests. "
             "Run tests from vst/test directory or run generate_test_model.py first.");
        return;
    }

    REQUIRE(model.isLoaded());

    SECTION("produces output after buffer fill") {
        // Fill the buffer with a constant value
        float inputValue = 0.5f;
        for (int i = 0; i < ModelConfig::BUFFER_LENGTH; ++i) {
            model.processSample(inputValue);
        }

        // After buffer fill, model should produce inference output
        // The test model is designed to produce output different from input
        float output = model.processSample(inputValue);

        // Output should be non-zero (model is running)
        REQUIRE(output != 0.0f);

        // Output should be different from input (proves model transformed the signal)
        REQUIRE(output != inputValue);
    }

    SECTION("produces consistent output for same input") {
        // Reset and fill buffer
        model.reset();

        float inputValue = 0.3f;
        for (int i = 0; i < ModelConfig::BUFFER_LENGTH; ++i) {
            model.processSample(inputValue);
        }

        // Get first inference output
        float output1 = model.processSample(inputValue);

        // Reset and repeat
        model.reset();
        for (int i = 0; i < ModelConfig::BUFFER_LENGTH; ++i) {
            model.processSample(inputValue);
        }

        // Should get same output
        float output2 = model.processSample(inputValue);

        REQUIRE_THAT(output1, WithinAbs(output2, 0.0001f));
    }

    SECTION("output varies with input") {
        // Fill buffer with one value
        model.reset();
        float inputLow = 0.1f;
        for (int i = 0; i < ModelConfig::BUFFER_LENGTH + 1; ++i) {
            model.processSample(inputLow);
        }
        float outputLow = model.processSample(inputLow);

        // Fill buffer with different value
        model.reset();
        float inputHigh = 0.9f;
        for (int i = 0; i < ModelConfig::BUFFER_LENGTH + 1; ++i) {
            model.processSample(inputHigh);
        }
        float outputHigh = model.processSample(inputHigh);

        // Outputs should be different
        REQUIRE(outputLow != outputHigh);
    }

    SECTION("crossfade during transition period") {
        model.reset();

        float inputValue = 0.5f;

        // Fill buffer to just before transition
        for (int i = 0; i < ModelConfig::BUFFER_LENGTH - 1; ++i) {
            model.processSample(inputValue);
        }

        // Last passthrough sample
        float lastPassthrough = model.processSample(inputValue);
        REQUIRE_THAT(lastPassthrough, WithinAbs(inputValue, 0.0001f));

        // First inference sample (start of crossfade - mostly input)
        float firstInference = model.processSample(inputValue);
        // Should be close to input due to crossfade starting at t=0
        REQUIRE_THAT(firstInference, WithinAbs(inputValue, 0.1f));

        // After crossfade period, output should be pure model output
        for (int i = 1; i < ModelConfig::CROSSFADE_LENGTH; ++i) {
            model.processSample(inputValue);
        }
        float postCrossfade = model.processSample(inputValue);

        // Output should now be purely from model (no crossfade blend)
        // Just verify it's different from input
        REQUIRE(postCrossfade != inputValue);
    }
}

TEST_CASE("NeuralFIRModel error handling", "[neural_model]") {
    NeuralFIRModel model;

    SECTION("getLastError reports file not found") {
        bool loaded = model.loadModel("/nonexistent/path/model.json");
        REQUIRE_FALSE(loaded);
        REQUIRE_FALSE(model.getLastError().empty());
        REQUIRE(model.getLastError().find("Failed to open") != std::string::npos);
    }

    SECTION("clearError clears the error message") {
        model.loadModel("/nonexistent/path/model.json");
        REQUIRE_FALSE(model.getLastError().empty());
        model.clearError();
        REQUIRE(model.getLastError().empty());
    }
}
